spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/project
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
url-shortener.base-url=http://localhost.helloworld/testingthe-code:8080
url-shortener.code-length=7
url-shortener.max-generation-attempts=8
url-shortener.cleanup-delay-ms=60000
